Update lookup table
proteanstudio/contrast-tools pull request #12
Opened 2022-07-17 19:47 UTC by sondr3

Looks like there's been an update to the values that is used in the lookup table, I've updated  and replaced the values to match [this](https://github.com/Myndex/apca-w3/blob/3695cc8d6342e8e13b4c3f0a7c97c437b41435a9/images/APCAlookupByFont.jpeg) table.

2022-07-19 00:55 UTC, abdulmhamid commented
@sondr3 Thank you for submitting this pull request — this is something that we've been planning to do.  We can get this merged after two more changes are made.

1. Please change the value of the 21px/700 cell to 50 to match the new table.
2. Please rebase your changes from the `develop` branch to preserve the history.  All code goes through `develop` before being merged to `main`.

2022-07-19 01:04 UTC, abdulmhamid requested changes
@sondr3 Thank you for submitting this pull request — we have been planning to update the lookup table.  We will need two more changes before we can get this merged.

1. Please update the cell value at 21px/700 to `50` to match the new table.
2. Please rebase your branch with `develop` to maintain the history. All changes are pushed through the `develop` branch before being pushed to `main`.  We will add some contributing guidelines in a few weeks that will outline that process.

2022-07-19 10:49 UTC, sondr3 commented
Done and done! I also double checked the values again, just to make sure :smile:

2022-07-21 00:30 UTC, abdulmhamid approved these changes

2022-07-21 00:30 UTC, merged

2022-07-21 00:30 UTC, abdulmhamid commented
Perfect. Thanks again for the PR!